aklinker1/vite-plugin-web-extension

README.md, lib/index.ts
The auto-launching behavior can be undesirable in many circumstances like:
- using alternative browsers like edge (my setup)
- using WSL (also my setup)
I've added a `skipAutoInstall` option to easily disable auto-installing and launching to deal with that :)
=> feat: add a `skipAutoLaunch` option

lib/index.ts
permissions fields is not required in manifest.json
See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions
but fail when run `vite dev` caused by undefined of
`transformedManifest.permissions` if unset permissions field in manifest.json
---
`pnpm build ` passed with `demos/{localization,vanilla,vue}`
=> fix: permissions field is not required but `vite dev` requires

lib/index.ts
I try to add the react content script application in my manifest.json but when I add the reference to the .tsx file this does not work.
The solution I have found is to inject my content-script from the background script. 
I have added .tsx to scriptExtensions so that tsx files included in additionalInputs are treated as scripts.
- Config:
`
additionalInputs: [
'content-scripts/index.tsx'
]
`
- Build output without tsx in scriptExtension:
`
/dist/content-scripts.index.html
`
- Build output with tsx in scriptExtension:
`
/dist/content-scripts.index.js
`
If someone has an approach to use the tsx from the manifest.json I think it would be good to add it to support both in additionalInputs and in the manifest.json a react application.
=> feat(react): add tsx extension in scriptExtensions

lib/decs.d.ts, lib/index.ts, lib/package.json
Hi,
I had trouble with `import webExtension from 'vite-plugin-web-extension'` in my 'vite.config.ts' from my TypeScript project which has `"type": "module"` set in `package.json`. The problem was with the default import of a function (`TypeError: webExtension is not a function`). It may have been due to my TypeScript configuration but I did not manage to find a working configuration. `webExtension` was being set to an object with properties `default` and `readJsonFile` rather than to just the default export as expected.
I managed to fix this in my fork by changing the `lib` package to a [Dual CommonJS/ES module package](https://nodejs.org/api/packages.html#dual-commonjses-module-packages), using [Approach #2: Isolate state](https://nodejs.org/api/packages.html#approach-2-isolate-state). …
=> Change to ES Modules format (as Dual ESM/CJS package)

packages/vite-plugin-web-extension/src/build-script.ts
These internal builds already inherit the root vite config file's configuration, it is passed down through the extension.
So all we need to do is tell vite to not discover any config files, and the recursion will break.
This closes #56 (the infinite loop half of the issue).
=> fix: ignore `vite.config.ts` files for internal builds

packages/vite-plugin-web-extension/index.ts
This closes #63 
On windows, if you run `web-ext` with a relative path like `"dist"` instead of `"C:\Path\to\dist"`, it will try and install the chrome extension relative to your chrome install directory. So we just need to pass in a absolute path.
=> fix: Open browser with absolute path to extension

packages/vite-plugin-web-extension/src/plugins/hmr-rewrite-plugin.ts, packages/vite-plugin-web-extension/src/plugins/manifest-loader-plugin.ts
This closes #79 
For this component:
The `src` attribute has the full URL instead of just the absolute path.
> Vite logs a warning that I'm importing a asset from the public directory, but it still proves the fix works.
=> fix: Use correct origin for assets in dev mode

docs/guide/index.md, packages/create-vite-plugin-web-extension/templates/svelte-js/jsconfig.json, packages/create-vite-plugin-web-extension/templates/svelte-js/package.json, packages/create-vite-plugin-web-extension/templates/svelte-js/src/background.js, packages/create-vite-plugin-web-extension/templates/svelte-js/src/manifest.json, packages/create-vite-plugin-web-extension/templates/svelte-js/src/pages/Popup.svelte, packages/create-vite-plugin-web-extension/templates/svelte-js/src/popup.css, packages/create-vite-plugin-web-extension/templates/svelte-js/src/popup.html, packages/create-vite-plugin-web-extension/templates/svelte-js/src/popup.js, packages/create-vite-plugin-web-extension/templates/svelte-js/src/vite.env.d.ts, packages/create-vite-plugin-web-extension/templates/svelte-js/svelte.config.js, packages/create-vite-plugin-web-extension/templates/svelte-js/vite.config.js, packages/create-vite-plugin-web-extension/templates/svelte-ts/package.json, packages/create-vite-plugin-web-extension/templates/svelte-ts/src/background.ts, packages/create-vite-plugin-web-extension/templates/svelte-ts/src/manifest.json, packages/create-vite-plugin-web-extension/templates/svelte-ts/src/pages/Popup.svelte, packages/create-vite-plugin-web-extension/templates/svelte-ts/src/popup.css, packages/create-vite-plugin-web-extension/templates/svelte-ts/src/popup.html, packages/create-vite-plugin-web-extension/templates/svelte-ts/src/popup.ts, packages/create-vite-plugin-web-extension/templates/svelte-ts/src/vite.env.d.ts, packages/create-vite-plugin-web-extension/templates/svelte-ts/svelte.config.js, packages/create-vite-plugin-web-extension/templates/svelte-ts/tsconfig.json, packages/create-vite-plugin-web-extension/templates/svelte-ts/tsconfig.node.json, packages/create-vite-plugin-web-extension/templates/svelte-ts/vite.config.ts, packages/create-vite-plugin-web-extension/templates/templates.json, packages/create-vite-plugin-web-extension/test-all.sh
This PR adresses #86.
I’ve adhered as much as possible to the current templates regarding the structure and some minor criteria (import css in the html file, don't export the app in the entrypoint, etc).
It is mostly based on Vite's Svelte, although I modified the `tsconfig.json` a bit to conform to the rest.
It also includes, as per Vite's default, a jsconfig for the js only file, which enables IDE typechecking.
You can test it by cloning the `add-svelte-template-test` branch.
I've ran the `test-all.sh` using `gitbash` and it looked fine. I only ran into trouble with the vue-js/ts ones, which appeared blank, but that also happened on a freshly cloned repo, so I assume that's something else.
Please let me know if there's any issue. I've never worked on a monorepo before!
---
Also, I just …
=> chore: Add svelte template to starter kit

packages/vite-plugin-web-extension/src/build/build-context.ts, packages/vite-plugin-web-extension/src/build/getViteConfigsForInputs.ts, packages/vite-plugin-web-extension/src/plugins/manifest-loader-plugin.ts
This closes #96.
I tried using other approaches than using library mode, but could not get anything else to work. So I stuck with library mode, and just defined a replacement for the `process.env.NODE_ENV` reference.
=> fix: Define `process.env.NODE_ENV` for lib mode builds

packages/vite-plugin-web-extension/src/plugins/hmr-rewrite-plugin.ts
=> fix: Normalize input module IDs to fix HMR on Windows

docs/config/plugin-options.md, packages/e2e/e2e.test.ts, packages/vite-plugin-web-extension/src/options.ts, packages/vite-plugin-web-extension/src/plugins/manifest-loader-plugin.ts
This adds a configuration option to allow projects to customize the manifest after rendering in the event changes are needed from the manifest which the plugin produces.
This resolves/is a result of the [discussion here](https://github.com/aklinker1/vite-plugin-web-extension/discussions/122).
=> feat: Add `transformManifest` option

packages/vite-plugin-web-extension/src/index.ts
Last PR missed adding `transformManifest` to the `internalOptions`.
=> fix: add `transformManifest` to `internalOptions`

docs/guide/localization.md
The localization page contains a small typo : `manfiest.json` -> `manifest.json`
=> docs: Fix typo in documentation

packages/vite-plugin-web-extension/package.json, packages/vite-plugin-web-extension/src/build/getViteConfigsForInputs.ts, packages/vite-plugin-web-extension/src/build/renderManifest.test.ts, packages/vite-plugin-web-extension/src/build/renderManifest.ts
This closes #167. If you add `public:` in front of an entrypoint in your manifest, the plugin will render it to the final manifest without processing the file.
For example, if you want to load jquery into a content script, and have downloaded a version locally:
```
public/
vendor/
jquery.min.js
src/
my/
content-script.ts
```
```jsonc
{
// ...
"content_scripts": [
{
"matches": [...],
"js": ["public:vendor/jquery.min.js", "src/my/content-script.ts"],
}
]
}
```
If possible, I would recommend just using the NPM modules, but sometimes it's easier to just keep using a version from a CDN.
=> feat: Don't transform entrypoints prefixed with `public:`

packages/vite-plugin-web-extension/package.json, packages/vite-plugin-web-extension/src/plugins/manifest-loader-plugin.ts
Vite started calling a hook in dev mode that it wasn't calling before in v5. Released v4.1.1-alpha1 for testing, confirmed that it fixes #172.
=> fix: Vite 5 HMR not working

packages/vite-plugin-web-extension/src/manifest-validation.ts
In the last two days builds time out due to the issue with the website  `https://json.schemastore.org`. 
I propose updating the SCHEMA_URL from its current `https://json.schemastore.org/chrome-manifest` URL to the raw GitHub content URL  `https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/chrome-manifest.json`. GitHub has superior availability and it's a smaller change that we will encounter this issue again. 
```
...
vite v5.1.0 building for development...
✓ 1 modules transformed.
dist/src/index.css  26.42 kB │ gzip: 4.85 kB
✓ built in 186ms
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
at JSON.parse (<anonymous>)
at …
```
=> FIX - createManifestValidator failing because schemastore.org is returning 503

packages/create-vite-plugin-web-extension/templates/react-js/package.json, packages/create-vite-plugin-web-extension/templates/react-js/vite.config.js, packages/create-vite-plugin-web-extension/templates/react-ts/package.json, packages/create-vite-plugin-web-extension/templates/react-ts/vite.config.ts
This pull request is a hot-fix for the issues presented here:
https://github.com/aklinker1/vite-plugin-web-extension/issues/177
This isn't meant to be a permanent fix, but the defaults should just work out of the box until a the actual resolution is found for https://github.com/vitejs/vite-plugin-react-swc.
=> fix: Changed react plugin to non-swc variation

packages/vite-plugin-web-extension/src/plugins/hmr-rewrite-plugin.ts
This PR updates serializeDefine to latest version from vite. It fixes compilation errors when define contains string values. 
```
[vite:define] Transform failed with 1 error:
error: Invalid define value (must be an entity name or valid JSON syntax)
```
For some unknown reasons it's not working only in combination with @vitejs/plugin-react, however, the issue is with `(${val})` syntax, that esbuild doesn't accept.
```
node@18.18.2
vite@^5.2.12
vite-plugin-web-extension@4.1.3
@vitejs/plugin-react@^4.3.0
```
```ts
export default defineConfig({
define: {
"process.env.REACT_APP_BASEURL": '""'
},
plugins: [
react(),
webExtension({
manifest: generateManifest,
}),
]
})
```
=> Update serializeDefine implementation from upstream vite

packages/vite-plugin-web-extension/src/extension-runner/web-ext-runner.ts
I spent a considerable amount of time diagnosing why I wasn't getting expected results from web-ext using this project.  After reviewing the source, I discovered that the options I had configured were being overwritten by the code before being passed to web-ext.  
This change suggestion moves the feedback down below when the final changes are made to the config, so that the verbose logging showing what's being sent is accurate.
=> Refactored so that logging shows final config being sent to web-ext-run

docs/config/plugin-options.md, packages/vite-plugin-web-extension/src/index.ts, packages/vite-plugin-web-extension/src/options.ts, packages/vite-plugin-web-extension/src/plugins/manifest-loader-plugin.ts
This PR adds the following plugin option:
```ts
bundleInfoJsonPath?: string
```
If set, the plugin will write a JSON file containing information about the built bundles to the specified path in the output directory. This can for example be useful for dynamically injecting content scripts/styles from background scripts.
=> feat: Added `bundleInfoJsonPath` plugin option

packages/create-vite-plugin-web-extension/templates/svelte-js/package.json, packages/create-vite-plugin-web-extension/templates/svelte-js/src/popup.js, packages/create-vite-plugin-web-extension/templates/svelte-ts/package.json, packages/create-vite-plugin-web-extension/templates/svelte-ts/src/popup.ts
This migrates both svelte templates to svelte v5 release. It might fix #215
=> chore: migrate svelte to v5 release

packages/create-vite-plugin-web-extension/templates/react-ts/package.json, packages/create-vite-plugin-web-extension/templates/svelte-ts/package.json, packages/create-vite-plugin-web-extension/templates/vanilla-ts/package.json, packages/create-vite-plugin-web-extension/templates/vue-ts/package.json
The typescript package doesn't follow semver, see https://github.com/microsoft/TypeScript/issues/14116
Every minor version bump can lead to breaking changes, see https://github.com/microsoft/TypeScript/wiki/Breaking-Changes
Use tilde instead of caret to ensure that npm doesn't install beyond the specified minor version.
=> chore: Use tilde for typescript versions in templates

docs/config/plugin-options.md, packages/vite-plugin-web-extension/src/index.ts, packages/vite-plugin-web-extension/src/options.ts, packages/vite-plugin-web-extension/src/plugins/manifest-loader-plugin.ts
I want to have some post-build actions executed as a part of serve of build process, and as I can see there is no such possibility yet (described here #218). I was unable to achieve that using both plugins (they are executed for every entrypoint group, which is not the case) and rollup hook overrides.
So, I've added `onBundleReady` callback to the `options`, which is called for every extension rebuild.
```ts
onBundleReady?: void | Promise<void>
```
Feedback are welcome, I am ready to improve API or something else
=> feat: Implement callback that is called after parent build is completed

packages/vite-plugin-web-extension/package.json, packages/vite-plugin-web-extension/src/options.ts, pnpm-lock.yaml
Hey! Today I wrote a script that generates TypeScript definitions for the `web-ext` command options, using the source code of `web-ext` as the source of truth.
- The repo: https://github.com/aleclarson/web-ext-option-types
- Example type definitions: https://github.com/aleclarson/web-ext-option-types/blob/main/npm/index.d.ts
Its output is published as the `web-ext-option-types` package. The plan is to have it update periodically using GitHub Actions.
Let me know if you have any questions!
=> feat: add type safety to `webExtConfig` options

packages/vite-plugin-web-extension/package.json, packages/vite-plugin-web-extension/src/options.ts, pnpm-lock.yaml
A few tweaks to the new `webExtConfig` types.
- Since `reload` is [always false](https://github.com/aleclarson/vite-plugin-web-extension/blob/284992dec99164823b53f539a35984927b937a8b/packages/vite-plugin-web-extension/src/extension-runner/web-ext-runner.ts#L40), exclude it from the config.
- Add the `firefox` option, but deprecate it, preferring `firefoxBinary` instead. (Related to https://github.com/wxt-dev/web-ext-run/pull/7)
- Export the `WebExtConfig` interface type containing these tweaks.
=> fix(types): add `WebExtConfig` type, omit `reload` option, deprecate `firefox` option

packages/vite-plugin-web-extension/src/build/build-context.ts, packages/vite-plugin-web-extension/src/index.ts
When the Vite dev server restarts, this plugin was not working as expected. Most notably, the browser would not be re-opened, which is what drew my attention to this issue.
The fix is pretty straight-forward. Avoid keeping `process.env.VITE_PLUGIN_WEB_EXTENSION_CHILD_BUILD` set after the child builds have finished. This PR sets it to an empty string, so the `manifestLoaderPlugin` can be called again while the dev server is restarting.
=> fix(dev): re-enable manifestLoaderPlugin after child builds are done

packages/vite-plugin-web-extension/package.json, pnpm-lock.yaml
Add support for Vite 7 ([Migration from v6](https://vite.dev/guide/migration.html#migration-from-v6))
I tested it on personal projects, and it seems to work well without any changes needed. :)
=> chore(deps): add vite v7 support
